# Generated by Django 5.0.1 on 2024-01-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_posts_user_remove_album_artista_remove_musica_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comentario',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
